/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SceneNewRouteImport } from './routes/scene/new'
import { Route as SceneIdRouteImport } from './routes/scene/$id'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthConfirmResetRouteImport } from './routes/auth/confirm-reset'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SceneNewRoute = SceneNewRouteImport.update({
  id: '/scene/new',
  path: '/scene/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SceneIdRoute = SceneIdRouteImport.update({
  id: '/scene/$id',
  path: '/scene/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmResetRoute = AuthConfirmResetRouteImport.update({
  id: '/auth/confirm-reset',
  path: '/auth/confirm-reset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/confirm-reset': typeof AuthConfirmResetRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/scene/$id': typeof SceneIdRoute
  '/scene/new': typeof SceneNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/confirm-reset': typeof AuthConfirmResetRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/scene/$id': typeof SceneIdRoute
  '/scene/new': typeof SceneNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/confirm-reset': typeof AuthConfirmResetRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/scene/$id': typeof SceneIdRoute
  '/scene/new': typeof SceneNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/confirm-reset'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/scene/$id'
    | '/scene/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/confirm-reset'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/scene/$id'
    | '/scene/new'
  id:
    | '__root__'
    | '/'
    | '/auth/confirm-reset'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/scene/$id'
    | '/scene/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthConfirmResetRoute: typeof AuthConfirmResetRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  SceneIdRoute: typeof SceneIdRoute
  SceneNewRoute: typeof SceneNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene/new': {
      id: '/scene/new'
      path: '/scene/new'
      fullPath: '/scene/new'
      preLoaderRoute: typeof SceneNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene/$id': {
      id: '/scene/$id'
      path: '/scene/$id'
      fullPath: '/scene/$id'
      preLoaderRoute: typeof SceneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm-reset': {
      id: '/auth/confirm-reset'
      path: '/auth/confirm-reset'
      fullPath: '/auth/confirm-reset'
      preLoaderRoute: typeof AuthConfirmResetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthConfirmResetRoute: AuthConfirmResetRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  SceneIdRoute: SceneIdRoute,
  SceneNewRoute: SceneNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
