/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SceneNewRouteImport } from './routes/scene/new'
import { Route as SceneIdRouteImport } from './routes/scene/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SceneNewRoute = SceneNewRouteImport.update({
  id: '/scene/new',
  path: '/scene/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SceneIdRoute = SceneIdRouteImport.update({
  id: '/scene/$id',
  path: '/scene/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scene/$id': typeof SceneIdRoute
  '/scene/new': typeof SceneNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scene/$id': typeof SceneIdRoute
  '/scene/new': typeof SceneNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scene/$id': typeof SceneIdRoute
  '/scene/new': typeof SceneNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/scene/$id' | '/scene/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scene/$id' | '/scene/new'
  id: '__root__' | '/' | '/scene/$id' | '/scene/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SceneIdRoute: typeof SceneIdRoute
  SceneNewRoute: typeof SceneNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene/new': {
      id: '/scene/new'
      path: '/scene/new'
      fullPath: '/scene/new'
      preLoaderRoute: typeof SceneNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene/$id': {
      id: '/scene/$id'
      path: '/scene/$id'
      fullPath: '/scene/$id'
      preLoaderRoute: typeof SceneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SceneIdRoute: SceneIdRoute,
  SceneNewRoute: SceneNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
